image: devillex/docker-firebase

stages:
  - deploy

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - firebase use dhxweb --token $FIREBASE_DEPLOY_KEY
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_DEPLOY_KEY