files:
  - source: /
    ignore:
      - /css
      - /fonts
      - /images
      - /js
      - /public
      - /rs-plugin
      - /video
      - .*
      - firebase.json
      - /ja
      - /ko
      - /zh*
      - /ach
      - LICENSE
      - privacy.pdf
    translation: /%two_letters_code%/%original_file_name%
