files:
  - source: /
    ignore:
      - /css
      - /fonts
      - /images
      - /js
      - /public
      - /rs-plugin
      - /video
      - .*
      - firebase.json
    translation: '%two_letters_code%/%original_file_name%'
